theme: jekyll-theme-minimal

title: [A Jogállamról]
description: ["Egy óra a jogállamról. Neked mit jelent?"]
logo: [liberta-dexpression-christophe-kiciak.jpg]
show_downloads: [true]
google_analytics: [G-D4FBCGWV4R]
